<?php

declare(strict_types=1);

return [
    'escapeshellarg',
    'escapeshellcmd',
    'exec',
    'eval',
    'passthru',
    'system',
    'shell_exec',
    'popen',
    'proc_open',
    'pcntl_exec',
    'proc_nice',
    'proc_terminate',
    'proc_close',
    'pfsockopen',
    'fsockopen',

    'md5',
    'md5_file',
    'sha1',
    'sha1_file',

    'user_error',
    'trigger_error',
    'error_clear_last',
    'error_log',
    'error_reporting',
    'restore_error_handler',
    'restore_exception_handler',
    'set_error_handler',
    'set_exception_handler',

    'ini_set',
    'ini_restore',
    'ini_alter',
    'ini_parse_quantity',
    'ini_get_all',
    'ini_get',
    'php_sapi_name',
    'php_uname',

    'flush',
    'ob_clean',
    'ob_end_clean',
    'ob_end_flush',
    'ob_flush',
    'ob_get_clean',
    'ob_get_contents',
    'ob_get_flush',
    'ob_get_length',
    'ob_get_level',
    'ob_get_status',
    'ob_gzhandler',
    'ob_implicit_flush',
    'ob_list_handlers',
    'ob_start',
    'output_add_rewrite_var',
    'output_reset_rewrite_vars',

    'get_cfg_var',
    'get_current_user',
    'get_defined_constants',
    'get_extension_funcs',
    'get_include_path',
    'get_included_files',
    'get_loaded_extensions',
    'get_required_files',
    'get_resources',

    'getmyinode',
    'getlastmod',
    'getmygid',
    'getmypid',
    'getmyuid',
    'getrusage',

    'header',
    'header_remove',
    'headers_sent',
    'headers_list',
    'getallheaders',
    'get_headers',
    'apache_request_headers',

    'http_response_code',
    'setrawcookie',
    'setcookie',
    'fastcgi_finish_request',
    'fpm_get_status',
    'date_default_timezone_set',
    'date_default_timezone_get',

    'exit',
    'die',
    'var_dump',
    'var_export',
    'print_r',

    '__halt_compiler',
    'ignore_user_abort',

    'connection_status',
    'connection_aborted',
    'clearstatcache',

    'register_shutdown_function',
    'register_tick_function',
    'unregister_tick_function',

    'session_abort',
    'session_cache_expire',
    'session_cache_limiter',
    'session_commit',
    'session_create_id',
    'session_decode',
    'session_destroy',
    'session_encode',
    'session_gc',
    'session_get_cookie_params',
    'session_id',
    'session_module_name',
    'session_name',
    'session_regenerate_Id',
    'session_register_shutdown',
    'session_reset',
    'session_save_path',
    'session_set_cookie_params',
    'session_start',
    'session_status',
    'session_unset',
    'session_write_close',
    'session_set_save_handler',

    'memory_reset_peak_usage',
    'set_time_limit',
    'set_include_path',
    'dl',
    'mail',
    'putenv',
    'cli_set_process_title',
    'gc_disable',
    'gc_enable',
    'gc_mem_caches',
    'setlocale',
    'mb_internal_encoding',
    'mb_regex_encoding',
];
